# Generated by Django 5.0.7 on 2026-07-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambiente',
            name='exige_checkin',
            field=models.BooleanField(default=False, help_text='Se marcado, reservas deste ambiente são liberadas automaticamente por no-show quando ninguém confirma o check-in dentro da tolerância.', verbose_name='Exige check-in'),
        ),
        migrations.AddField(
            model_name='ambiente',
            name='tolerancia_checkin_minutos',
            field=models.PositiveIntegerField(default=15, help_text='Minutos após o início da reserva antes de liberar o ambiente automaticamente por no-show.', verbose_name='Tolerância de check-in (minutos)'),
        ),
        migrations.AddField(
            model_name='historicalambiente',
            name='exige_checkin',
            field=models.BooleanField(default=False, help_text='Se marcado, reservas deste ambiente são liberadas automaticamente por no-show quando ninguém confirma o check-in dentro da tolerância.', verbose_name='Exige check-in'),
        ),
        migrations.AddField(
            model_name='historicalambiente',
            name='tolerancia_checkin_minutos',
            field=models.PositiveIntegerField(default=15, help_text='Minutos após o início da reserva antes de liberar o ambiente automaticamente por no-show.', verbose_name='Tolerância de check-in (minutos)'),
        ),
    ]
