# Generated by Django 5.0.7 on 2026-07-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreserva',
            name='checkin_confirmado_em',
            field=models.DateTimeField(blank=True, help_text='Preenchido quando o solicitante confirma presença. Usado para liberar a sala automaticamente em caso de no-show em ambientes que exigem check-in.', null=True, verbose_name='Check-in confirmado em'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='checkin_confirmado_em',
            field=models.DateTimeField(blank=True, help_text='Preenchido quando o solicitante confirma presença. Usado para liberar a sala automaticamente em caso de no-show em ambientes que exigem check-in.', null=True, verbose_name='Check-in confirmado em'),
        ),
        migrations.AlterField(
            model_name='historicalreserva',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('concluida', 'Concluída'), ('expirada', 'Expirada (no-show)')], default='confirmada', max_length=12),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('concluida', 'Concluída'), ('expirada', 'Expirada (no-show)')], default='confirmada', max_length=12),
        ),
    ]
