# Generated by Django 5.0.7 on 2026-07-19 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0002_historicalreserva_checkin_confirmado_em_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalreserva",
            name="notificar_email",
        ),
        migrations.RemoveField(
            model_name="reserva",
            name="notificar_email",
        ),
    ]
