# Generated by Django 5.0.7 on 2026-07-19 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("keys", "0002_backfill_chaves_ambientes_existentes"),
    ]

    operations = [
        migrations.AddField(
            model_name="chave",
            name="atraso_notificado_em",
            field=models.DateTimeField(
                blank=True,
                help_text="Quando o alerta de chave não devolvida foi enviado ao vigilante (evita reenvio repetido).",
                null=True,
            ),
        ),
    ]
