# Generated by Django 5.0.7 on 2026-07-19 23:10 — editado à mão para incluir a
# migração de dados abaixo (a ação "repor" foi removida: nenhuma chave deve mais
# ficar parada no status intermediário "devolvida").

from django.db import migrations, models


def converter_devolvidas_em_disponiveis(apps, schema_editor):
    """
    A ação "repor" foi removida (devolver já deixa a chave disponível direto, para
    qualquer perfil). Qualquer chave que porventura tenha ficado parada no status
    "devolvida" (ex.: fluxo antigo interrompido, ou edição manual via PATCH antes
    desta mudança) passa a "disponível" — exatamente o que "repor" faria.
    """
    Chave = apps.get_model("keys", "Chave")
    Chave.objects.filter(status="devolvida").update(
        status="disponivel",
        reserva_atual=None,
        retirada_em=None,
        retirada_por=None,
        atraso_notificado_em=None,
    )


def reverter_noop(apps, schema_editor):
    # Não há como saber quais chaves estavam "devolvida" antes da migração acima —
    # reverter não tenta recriar esse estado, só existe para permitir "migrate zero".
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("keys", "0003_chave_atraso_notificado_em"),
    ]

    operations = [
        migrations.RunPython(converter_devolvidas_em_disponiveis, reverter_noop),
        migrations.AlterField(
            model_name="chave",
            name="status",
            field=models.CharField(
                choices=[("disponivel", "Disponível"), ("ocupada", "Ocupada")],
                default="disponivel",
                max_length=20,
            ),
        ),
    ]
