# Generated by Django 5.0.7 on 2026-07-19 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("keys", "0004_alter_chave_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chave",
            name="atraso_notificado_em",
        ),
    ]
