# Generated by Django 5.0.7 on 2026-07-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0003_remove_historicalreserva_notificar_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalreserva",
            name="reservado_para_categoria",
            field=models.CharField(
                blank=True,
                choices=[
                    ("professor", "Professor"),
                    ("instrutor", "Instrutor"),
                    ("cliente", "Cliente"),
                    ("limpeza", "Limpeza"),
                    ("manutencao", "Manutenção"),
                ],
                max_length=20,
                verbose_name="Reservado para",
            ),
        ),
        migrations.AddField(
            model_name="historicalreserva",
            name="reservado_para_nome",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Nome de quem vai usar a sala"
            ),
        ),
        migrations.AddField(
            model_name="historicalreserva",
            name="reservado_para_telefone",
            field=models.CharField(
                blank=True,
                max_length=20,
                verbose_name="Telefone de quem vai usar a sala",
            ),
        ),
        migrations.AddField(
            model_name="reserva",
            name="reservado_para_categoria",
            field=models.CharField(
                blank=True,
                choices=[
                    ("professor", "Professor"),
                    ("instrutor", "Instrutor"),
                    ("cliente", "Cliente"),
                    ("limpeza", "Limpeza"),
                    ("manutencao", "Manutenção"),
                ],
                max_length=20,
                verbose_name="Reservado para",
            ),
        ),
        migrations.AddField(
            model_name="reserva",
            name="reservado_para_nome",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Nome de quem vai usar a sala"
            ),
        ),
        migrations.AddField(
            model_name="reserva",
            name="reservado_para_telefone",
            field=models.CharField(
                blank=True,
                max_length=20,
                verbose_name="Telefone de quem vai usar a sala",
            ),
        ),
    ]
