# Generated by Django 5.0.7 on 2026-07-17 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LogAuditoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "acao",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("criacao", "Criação"),
                            ("atualizacao", "Atualização"),
                            ("cancelamento", "Cancelamento"),
                            ("exclusao", "Exclusão"),
                            ("exportacao", "Exportação"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "entidade",
                    models.CharField(
                        help_text="Nome do modelo/entidade afetada, ex.: 'Reserva'.",
                        max_length=100,
                    ),
                ),
                ("entidade_id", models.CharField(blank=True, max_length=50, null=True)),
                ("descricao", models.CharField(blank=True, max_length=255)),
                ("detalhes", models.JSONField(blank=True, default=dict)),
                ("endereco_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs_auditoria",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Auditoria",
                "verbose_name_plural": "Logs de Auditoria",
                "ordering": ["-criado_em"],
            },
        ),
    ]
