# Generated by Django 5.0.7 on 2026-07-17 16:57

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ambiente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("sala_aula", "Sala de Aula"),
                            ("auditorio", "Auditório"),
                            ("laboratorio", "Laboratório"),
                            ("sala_reuniao", "Sala de Reunião"),
                            ("outro", "Outro"),
                        ],
                        default="sala_aula",
                        max_length=20,
                    ),
                ),
                (
                    "localizacao",
                    models.CharField(
                        blank=True, help_text="Bloco, andar, ala etc.", max_length=200
                    ),
                ),
                ("capacidade", models.PositiveIntegerField(default=0)),
                (
                    "recursos",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de recursos disponíveis, ex.: ['Projetor', 'Ar-condicionado', 'Quadro branco']",
                    ),
                ),
                ("descricao", models.TextField(blank=True)),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="ambientes/"),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Ambiente",
                "verbose_name_plural": "Ambientes",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalAmbiente",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("sala_aula", "Sala de Aula"),
                            ("auditorio", "Auditório"),
                            ("laboratorio", "Laboratório"),
                            ("sala_reuniao", "Sala de Reunião"),
                            ("outro", "Outro"),
                        ],
                        default="sala_aula",
                        max_length=20,
                    ),
                ),
                (
                    "localizacao",
                    models.CharField(
                        blank=True, help_text="Bloco, andar, ala etc.", max_length=200
                    ),
                ),
                ("capacidade", models.PositiveIntegerField(default=0)),
                (
                    "recursos",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de recursos disponíveis, ex.: ['Projetor', 'Ar-condicionado', 'Quadro branco']",
                    ),
                ),
                ("descricao", models.TextField(blank=True)),
                ("foto", models.TextField(blank=True, max_length=100, null=True)),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(blank=True, editable=False)),
                ("atualizado_em", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Ambiente",
                "verbose_name_plural": "historical Ambientes",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
