# Generated by Django 5.0.7 on 2026-07-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConfiguracaoSistema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estilo_icone",
                    models.CharField(
                        choices=[
                            ("padrao", "Padrão (contorno)"),
                            ("contornado", "Contornado"),
                            ("preenchido", "Preenchido"),
                        ],
                        default="padrao",
                        max_length=20,
                    ),
                ),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuração do sistema",
                "verbose_name_plural": "Configurações do sistema",
            },
        ),
    ]
