# Generated by Django 5.0.7 on 2026-07-19 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("environments", "0002_ambiente_exige_checkin_and_more"),
        ("reservations", "0004_historicalreserva_reservado_para_categoria_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Chave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("disponivel", "Disponível"),
                            ("ocupada", "Ocupada"),
                            ("devolvida", "Devolvida"),
                        ],
                        default="disponivel",
                        max_length=20,
                    ),
                ),
                ("retirada_em", models.DateTimeField(blank=True, null=True)),
                ("devolvida_em", models.DateTimeField(blank=True, null=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "ambiente",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chave",
                        to="environments.ambiente",
                    ),
                ),
                (
                    "reserva_atual",
                    models.ForeignKey(
                        blank=True,
                        help_text="Reserva vinculada ao ciclo de retirada/devolução em andamento.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="reservations.reserva",
                    ),
                ),
                (
                    "retirada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Chave",
                "verbose_name_plural": "Chaves",
                "ordering": ["ambiente__nome"],
            },
        ),
    ]
