# Generated by Django 5.0.7 on 2026-07-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaluser",
            name="email",
        ),
        migrations.RemoveField(
            model_name="user",
            name="email",
        ),
        migrations.AlterField(
            model_name="historicaluser",
            name="telefone",
            field=models.CharField(
                blank=True,
                help_text="Formato com DDI e DDD, ex: 5511999999999. Principal contato do usuário no sistema.",
                max_length=20,
                verbose_name="Telefone (WhatsApp)",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="telefone",
            field=models.CharField(
                blank=True,
                help_text="Formato com DDI e DDD, ex: 5511999999999. Principal contato do usuário no sistema.",
                max_length=20,
                verbose_name="Telefone (WhatsApp)",
            ),
        ),
    ]
