# Generated by Django 5.0.7 on 2026-07-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_historicaluser_papel_alter_user_papel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaluser",
            name="papel",
            field=models.CharField(
                choices=[
                    ("admin", "Administrador"),
                    ("user", "Usuário"),
                    ("vigilante", "Guarita"),
                ],
                default="user",
                max_length=10,
                verbose_name="Papel",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="papel",
            field=models.CharField(
                choices=[
                    ("admin", "Administrador"),
                    ("user", "Usuário"),
                    ("vigilante", "Guarita"),
                ],
                default="user",
                max_length=10,
                verbose_name="Papel",
            ),
        ),
    ]
